# Generated by Django 5.1.6 on 2025-02-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'quadra',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado')], default='disponivel', max_length=20)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponiveis', to='quadra_facil.quadra')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_reservante', models.CharField(max_length=255)),
                ('telefone_reservante', models.CharField(max_length=15)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='quadra_facil.horario')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
